"use client";
import Image from "next/image";
import {useEffect,useMemo,useRef,useState} from "react";
import {ACTIVE_RESUME_KEY,LEGACY_RESUME_KEY,RESUME_LIBRARY_KEY,ResumeDocument,createResume,safeFilename,isResumeTemplate,migrateLegacyResume} from "@/lib/resume";

type Item={id:string;title:string;subtitle:string;period:string;description:string};
type CV={name:string;role:string,email:string;phone:string;city:string;summary:string;photo:string;experiences:Item[];education:Item[];courses:string[];skills:string[];languages:string[]};
type Template="essential"|"modern"|"executive";
type SectionKey="summary"|"experiences"|"education"|"skills"|"languages"|"courses";
const defaultOrder:SectionKey[]=["summary","experiences","education","skills","languages","courses"];
const uid=()=>Math.random().toString(36).slice(2,9);
const initial:CV={name:"Felipe Andrade",photo:"",role:"Desenvolvedor de Software",email:"felipe@email.com",phone:"(11) 99999-9999",city:"São Paulo, SP",summary:"Profissional apaixonado por tecnologia, com foco em criar soluções digitais modernas, eficientes e fáceis de usar.",experiences:[{id:"exp1",title:"Desenvolvedor Full Stack",subtitle:"Empresa Exemplo",period:"2024 — Atual",description:"Desenvolvimento de aplicações web, melhoria de experiências digitais e colaboração com equipes multidisciplinares."}],education:[{id:"edu1",title:"Análise e Desenvolvimento de Sistemas",subtitle:"Instituição de Ensino",period:"2023 — 2025",description:""}],courses:["Desenvolvimento Web"],skills:["JavaScript","TypeScript","React","Comunicação"],languages:["Português — Nativo"]};
const tabs=["Conteúdo","Design"] as const;
type ExperienceContext="pending"|"standard"|"first-job"|"informal"|"self-employed"|"partial";
type EducationContext="pending"|"standard"|"in-progress"|"no-exact-date"|"none"|"partial";
type CoursesContext="pending"|"standard"|"none"|"missing-details";
type LanguagesContext="pending"|"standard"|"none"|"partial";
type GuidanceContext={experience:ExperienceContext;education:EducationContext;courses:CoursesContext;languages:LanguagesContext};
const guidanceKey=(id:string)=>"curriculospro.guidance.v1:"+id;

export default function Editor(){
 const hydrated=useRef(false),activeId=useRef("");
 const [documentTitle,setDocumentTitle]=useState("Meu currículo");
 const [guidance,setGuidance]=useState<GuidanceContext>({experience:"pending",education:"pending",courses:"pending",languages:"pending"});
 const [cv,setCv]=useState(initial),[tab,setTab]=useState<(typeof tabs)[number]>("Conteúdo"),[template,setTemplate]=useState<Template>("essential"),[accent,setAccent]=useState("#087cf0"),[mobilePreview,setMobilePreview]=useState(false),[density,setDensity]=useState<"comfortable"|"compact">("comfortable"),[sectionOrder,setSectionOrder]=useState<SectionKey[]>(defaultOrder),[hidden,setHidden]=useState<SectionKey[]>([]);
 useEffect(()=>{try{const params=new URLSearchParams(location.search),mode=params.get("new"),requested=params.get("template");let docs:ResumeDocument[]=JSON.parse(localStorage.getItem(RESUME_LIBRARY_KEY)||"[]");let doc:ResumeDocument|undefined;if(mode==="blank"||mode==="example"){doc=createResume(mode,isResumeTemplate(requested)?requested:"essential");docs=[doc,...docs];localStorage.setItem(RESUME_LIBRARY_KEY,JSON.stringify(docs));history.replaceState({},"","/editor")}else{const id=localStorage.getItem(ACTIVE_RESUME_KEY);doc=docs.find(x=>x.id===id)||docs[0]}if(doc){activeId.current=doc.id;try{const g=JSON.parse(localStorage.getItem(guidanceKey(doc.id))||"null") as GuidanceContext|null;if(g)setGuidance({experience:g.experience||"pending",education:g.education||"pending",courses:g.courses||"pending",languages:g.languages||"pending"})}catch{};setDocumentTitle(doc.title);localStorage.setItem(ACTIVE_RESUME_KEY,doc.id);setCv({...initial,...doc.cv});setTemplate(doc.template);setAccent(doc.accent);setDensity(doc.density);setSectionOrder(doc.sectionOrder||defaultOrder);setHidden(doc.hidden||[])}else{const s=localStorage.getItem(LEGACY_RESUME_KEY);if(s){doc=migrateLegacyResume(s);docs=[doc];localStorage.setItem(RESUME_LIBRARY_KEY,JSON.stringify(docs));activeId.current=doc.id;setDocumentTitle(doc.title);localStorage.setItem(ACTIVE_RESUME_KEY,doc.id);setCv({...initial,...doc.cv});setTemplate(doc.template);setAccent(doc.accent);setDensity(doc.density);setSectionOrder(doc.sectionOrder);setHidden(doc.hidden)}}}catch{}finally{hydrated.current=true}},[]);
 useEffect(()=>{if(!hydrated.current)return;try{localStorage.setItem(LEGACY_RESUME_KEY,JSON.stringify({cv,template,accent,density,sectionOrder,hidden}));let docs:ResumeDocument[]=JSON.parse(localStorage.getItem(RESUME_LIBRARY_KEY)||"[]");let id=activeId.current;if(!id){const doc=createResume("blank",template);id=doc.id;activeId.current=id;docs=[doc,...docs];localStorage.setItem(ACTIVE_RESUME_KEY,id)}const now=new Date().toISOString(),found=docs.find(x=>x.id===id),next:ResumeDocument={id,title:documentTitle||found?.title||cv.name||"Meu currículo",createdAt:found?.createdAt||now,updatedAt:now,cv,template,accent,density,sectionOrder,hidden};docs=found?docs.map(x=>x.id===id?next:x):[next,...docs];localStorage.setItem(RESUME_LIBRARY_KEY,JSON.stringify(docs))}catch{}},[cv,template,accent,density,sectionOrder,hidden,documentTitle]);
 const goToStep=(id:string)=>{setTab("Conteúdo");setMobilePreview(false);requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"}))};
 useEffect(()=>{if(hydrated.current&&activeId.current)try{localStorage.setItem(guidanceKey(activeId.current),JSON.stringify(guidance))}catch{}},[guidance]);
 const printResume=()=>{const previous=document.title;document.title=safeFilename(documentTitle||cv.name||"curriculo")+"-CurriculosPRO";window.print();setTimeout(()=>{document.title=previous},500)};
 const assistant=useMemo(()=>{
  const emailOk=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(cv.email),phoneOk=[10,11].includes(cv.phone.replace(/\D/g,"").length);
  const expHas=cv.experiences.some(x=>x.title.trim()&&(x.subtitle.trim()||x.description.trim())),eduHas=cv.education.some(x=>x.title.trim()),skillsOk=cv.skills.filter(x=>x.trim()).length>=3;
  const resolved=[
   {ok:cv.name.trim().split(/\s+/).length>=2,label:"Identificação",tip:"Informe nome e sobrenome."},
   {ok:emailOk||phoneOk,label:"Contato",tip:"Informe pelo menos um contato válido."},
   {ok:cv.role.trim().length>=3,label:"Objetivo profissional",tip:"Informe sua área, função ou objetivo."},
   {ok:cv.summary.trim().length>=60,label:"Resumo",tip:"Apresente sua trajetória e pontos fortes em poucas linhas."},
   {ok:guidance.experience==="first-job"||expHas||["informal","self-employed"].includes(guidance.experience)&&expHas,label:"Experiência",tip:guidance.experience==="pending"?"Diga qual é sua situação profissional.":"Complete apenas as informações que realmente existirem."},
   {ok:guidance.education==="none"||eduHas,label:"Formação",tip:guidance.education==="pending"?"Diga como está sua formação.":"Informe o que souber com segurança."},
   {ok:skillsOk,label:"Competências",tip:"Liste habilidades que você realmente possui."},
   {ok:guidance.courses==="none"||guidance.courses!=="pending"&&cv.courses.some(x=>x.trim()),label:"Cursos",tip:guidance.courses==="pending"?"Diga se você tem cursos para informar.":"Esta seção é opcional."},
   {ok:guidance.languages==="none"||guidance.languages!=="pending"&&cv.languages.some(x=>x.trim()),label:"Idiomas",tip:guidance.languages==="pending"?"Diga se você quer informar idiomas.":"Informe apenas seu nível real."}
  ];
  const done=resolved.filter(x=>x.ok).length,score=Math.round(done/resolved.length*100),next=resolved.filter(x=>!x.ok).slice(0,3);
  return{checks:resolved,score,next,done,total:resolved.length}
 },[cv,guidance]); const completion=assistant.score;
 const journey=useMemo(()=>[
  {id:"step-personal",label:"Dados pessoais",done:!!cv.name.trim()&&(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(cv.email)||[10,11].includes(cv.phone.replace(/\D/g,"").length)),optional:false},
  {id:"step-summary",label:"Resumo",done:cv.summary.trim().length>=60,optional:true},
  {id:"step-experience",label:"Experiência",done:guidance.experience==="first-job"||cv.experiences.some(x=>x.title.trim()&&(x.subtitle.trim()||x.description.trim())),optional:true},
  {id:"step-education",label:"Formação",done:guidance.education==="none"||cv.education.some(x=>x.title.trim()),optional:true},
  {id:"step-skills",label:"Competências",done:cv.skills.filter(x=>x.trim()).length>=3,optional:true},
  {id:"step-review",label:"Revisão",done:false,optional:false}
 ],[cv,guidance]);
 const review=useMemo(()=>{
  const issues:{level:"required"|"recommended"|"optional";title:string;text:string}[]=[];
  const emailOk=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(cv.email),phoneDigits=cv.phone.replace(/\D/g,"");
  if(!cv.name.trim())issues.push({level:"required",title:"Informe seu nome",text:"O currículo precisa identificar você."});
  if(cv.email&&!emailOk)issues.push({level:"required",title:"Revise o e-mail",text:"O endereço informado não parece completo."});
  if(cv.phone&&![10,11].includes(phoneDigits.length))issues.push({level:"required",title:"Revise o telefone",text:"Inclua DDD e o número completo."});
  if(!cv.email&&!cv.phone)issues.push({level:"required",title:"Adicione um contato",text:"Informe pelo menos e-mail ou telefone para que possam falar com você."});
  if(cv.summary.trim().length>0&&cv.summary.trim().length<60)issues.push({level:"recommended",title:"Desenvolva um pouco o resumo",text:"Explique experiência, pontos fortes e objetivo com mais contexto."});
  if(cv.summary.length>650)issues.push({level:"recommended",title:"Enxugue o resumo",text:"Um resumo mais direto facilita a leitura inicial."});
  const incompleteExp=cv.experiences.filter(x=>x.title.trim()&&(!x.subtitle.trim()||!x.period.trim()||!x.description.trim())).length;
  if(incompleteExp)issues.push({level:"recommended",title:incompleteExp+" experiência(s) podem ser detalhadas",text:"Confira empresa, período e atividades quando essas informações existirem."});
  const blankItems=[...cv.experiences,...cv.education].filter(x=>!x.title.trim()&&!x.subtitle.trim()&&!x.period.trim()&&!x.description.trim()).length;
  if(blankItems)issues.push({level:"optional",title:"Há itens vazios",text:"Remova itens que você adicionou mas decidiu não preencher."});
  if(hasDuplicateSkills(cv.skills))issues.push({level:"recommended",title:"Competências repetidas",text:"Remova duplicatas para deixar a seção mais objetiva."});
  const hiddenWithContent=hidden.filter(k=>k==="summary"?!!cv.summary.trim():k==="experiences"?cv.experiences.length>0:k==="education"?cv.education.length>0:k==="skills"?cv.skills.some(Boolean):k==="languages"?cv.languages.some(Boolean):guidance.courses!=="none"&&cv.courses.some(Boolean));
  if(hiddenWithContent.length)issues.push({level:"optional",title:"Há conteúdo oculto",text:"Algumas informações preenchidas não aparecerão no PDF porque a seção está oculta."});
  return{issues,required:issues.filter(x=>x.level==="required").length,recommended:issues.filter(x=>x.level==="recommended").length}
 },[cv,hidden,guidance]);
 const set=<K extends keyof CV>(k:K,v:CV[K])=>setCv({...cv,[k]:v});
 const updateItem=(section:"experiences"|"education",id:string,key:keyof Item,value:string)=>setCv({...cv,[section]:cv[section].map(x=>x.id===id?{...x,[key]:value}:x)});
 const addItem=(section:"experiences"|"education")=>setCv({...cv,[section]:[...cv[section],{id:uid(),title:"",subtitle:"",period:"",description:""}]});
 const removeItem=(section:"experiences"|"education",id:string)=>setCv({...cv,[section]:cv[section].filter(x=>x.id!==id)});
 const addList=(key:"courses"|"skills"|"languages")=>set(key,[...cv[key],""]);
 const updateList=(key:"courses"|"skills"|"languages",index:number,value:string)=>set(key,cv[key].map((x,i)=>i===index?value:x));
 const removeList=(key:"courses"|"skills"|"languages",index:number)=>set(key,cv[key].filter((_,i)=>i!==index));
 const move=(section:"experiences"|"education",index:number,dir:-1|1)=>{const next=[...cv[section]],target=index+dir;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setCv({...cv,[section]:next})};
 const onPhoto=(file?:File)=>{if(!file||file.size>2_500_000)return;const reader=new FileReader();reader.onload=()=>{const img=new window.Image();img.onload=()=>{const canvas=document.createElement("canvas"),max=480,scale=Math.min(1,max/Math.max(img.width,img.height));canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d")?.drawImage(img,0,0,canvas.width,canvas.height);set("photo",canvas.toDataURL("image/jpeg",.82))};img.src=String(reader.result)};reader.readAsDataURL(file)};
 const moveSection=(key:SectionKey,dir:-1|1)=>{const i=sectionOrder.indexOf(key),target=i+dir;if(target<0||target>=sectionOrder.length)return;const next=[...sectionOrder];[next[i],next[target]]=[next[target],next[i]];setSectionOrder(next)};
 const toggleSection=(key:SectionKey)=>setHidden(hidden.includes(key)?hidden.filter(x=>x!==key):[...hidden,key]);
 const visible=(key:SectionKey)=>!hidden.includes(key)&&!(key==="courses"&&guidance.courses==="none");
 const formatPhone=(value:string)=>{const d=value.replace(/\D/g,"").slice(0,11);if(!d)return"";if(d.length<3)return"("+d;if(d.length<=6)return"("+d.slice(0,2)+") "+d.slice(2);if(d.length<=10)return"("+d.slice(0,2)+") "+d.slice(2,6)+"-"+d.slice(6);return"("+d.slice(0,2)+") "+d.slice(2,7)+"-"+d.slice(7)};
 const formatCity=(value:string)=>value.replace(/\s*\/\s*/g," / ").replace(/\s{2,}/g," ");
 return <main className="editor">
  <header className="editorHead"><a className="brand brandImage editorLogo" href="/"><Image src="/brand/logo-transparent.png" alt="CurriculosPRO" width={155} height={58} priority /></a><a className="backLibrary" href="/curriculos">← Meus currículos</a><input className="documentTitle" aria-label="Nome do currículo" value={documentTitle} onChange={e=>setDocumentTitle(e.target.value)}/><div className="progress"><i style={{width:completion+"%"}}/><span>{completion}% completo</span></div><div className="save">● Salvo neste dispositivo</div><button className="mobileView" onClick={()=>setMobilePreview(!mobilePreview)}>{mobilePreview?"Editar":"Visualizar"}</button><button onClick={printResume} className="download">Salvar em PDF ↓</button></header>
  <div className={"workspace "+(mobilePreview?"showPreview":"")}>
   <aside className="side">
    <div className="editorTabs">{tabs.map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
    {tab==="Conteúdo"?<div className="formBody">
      <div className="guidedJourney" aria-label="Jornada de construção do currículo"><div className="journeyIntro"><div><small>JORNADA GUIADA</small><b>Construa no seu ritmo</b></div><span>Você pode pular e voltar quando quiser.</span></div><div className="journeySteps">{journey.map((step,index)=><button type="button" key={step.id} className={step.done?"done":step.id==="step-review"?"review":""} onClick={()=>goToStep(step.id)}><i>{step.done?"✓":index+1}</i><span><b>{step.label}</b><small>{step.done?"Preenchido":step.optional?"Preencha se fizer sentido":"Recomendado"}</small></span></button>)}</div></div>
      <div id="step-personal" className="journeyAnchor sectionTitle"><span>01</span><div><h2>Informações pessoais</h2><p>Comece pelo essencial.</p></div></div>
      <div className="resumeAssistant"><div className="assistantTop"><div><small>ASSISTENTE DE CURRÍCULO</small><b>{assistant.score===100?"Currículo bem estruturado":assistant.score>=70?"Está ficando muito bom":assistant.score>=40?"Bom começo — continue":"Vamos construir passo a passo"}</b></div><strong>{assistant.done}/{assistant.total}</strong></div><div className="assistantMeter"><i style={{width:assistant.score+"%"}}/></div>{assistant.next.length>0?<div className="assistantNext"><span>PRÓXIMOS PASSOS</span>{assistant.next.map(x=><div key={x.label}><i>○</i><p><b>{x.label}</b><small>{x.tip}</small></p></div>)}</div>:<div className="assistantReady">✓ Informações essenciais preenchidas. Revise a prévia antes de gerar o PDF.</div>}<p className="assistantRule">Sugestões baseadas apenas no que você preencheu. O CurriculosPRO não inventa informações profissionais.</p></div>
      <div id="step-review" className={"journeyAnchor finalReview "+(review.required?"hasRequired":"ready")}><div className="reviewHead"><div><small>REVISÃO ANTES DO PDF</small><b>{review.required?review.required+" ponto(s) importante(s) para revisar":review.issues.length?"Currículo pronto para uma última conferência":"Tudo certo para revisar a prévia"}</b></div><span>{review.required?"Revisar":"✓"}</span></div>{review.issues.length>0&&<div className="reviewIssues">{review.issues.slice(0,4).map((x,i)=><div className={"reviewIssue "+x.level} key={x.title+i}><i>{x.level==="required"?"!":x.level==="recommended"?"•":"i"}</i><p><b>{x.title}</b><small>{x.text}</small></p></div>)}</div>}<p className="reviewFoot">Esta revisão verifica estrutura e preenchimento. Ela não decide se sua experiência é “boa” ou “ruim”.</p></div>
      <div className="formGuidance"><b>Preenchimento guiado</b><span>Os campos ajudam a manter telefone, contato e informações profissionais em um formato claro.</span></div><div className="photoControl"><div className="photoPreview">{cv.photo?<img src={cv.photo} alt="Foto do currículo"/>:<span>{cv.name.split(" ").slice(0,2).map(x=>x[0]).join("")||"CV"}</span>}</div><div><b>Foto profissional <small>opcional</small></b><p>Use uma foto clara e profissional. Você pode remover quando quiser.</p><label className="photoButton">Escolher foto<input type="file" accept="image/*" onChange={e=>onPhoto(e.target.files?.[0])}/></label>{cv.photo&&<button className="removePhoto" onClick={()=>set("photo","")}>Remover foto</button>}</div></div><div className="grid2"><Field label="Nome completo" placeholder="Ex.: Mariana Costa" autoComplete="name" value={cv.name} onChange={v=>set("name",v)}/><Field label="Título profissional" placeholder="Ex.: Analista Administrativo" value={cv.role} onChange={v=>set("role",v)}/><Field label="E-mail" type="email" inputMode="email" autoComplete="email" placeholder="nome@exemplo.com" hint="Use um e-mail profissional que você acessa." value={cv.email} onChange={v=>set("email",v.trim())}/><Field label="Telefone" type="tel" inputMode="tel" autoComplete="tel" placeholder="(16) 99999-1234" maxLength={15} hint="DDD + número. A formatação é automática." value={cv.phone} onChange={v=>set("phone",formatPhone(v))}/></div><Field label="Cidade / Estado" autoComplete="address-level2" placeholder="Ex.: Matão / SP" hint="Cidade e UF onde você mora ou busca oportunidades." value={cv.city} onChange={v=>set("city",formatCity(v))}/><div id="step-summary" className="journeyAnchor"/><Field area label="Resumo profissional" placeholder="Ex.: Profissional com experiência em atendimento, organização de rotinas e suporte administrativo..." hint="Em 3 a 5 linhas, destaque experiência, pontos fortes e objetivo." value={cv.summary} onChange={v=>set("summary",v)}/>{cv.summary.trim()&&cv.summary.trim().length<60&&<CoachTip title="Seu resumo pode contar um pouco mais" text="Tente combinar: sua área ou experiência + 2 pontos fortes reais + o tipo de contribuição ou oportunidade que busca."/>}
      <div id="step-experience" className="journeyAnchor"><SectionHead n="02" title="Experiência" subtitle="Vale emprego formal, trabalho autônomo, estágio, projeto ou experiência informal relevante." action={()=>addItem("experiences")}/><ContextChoice label="Qual situação combina mais com você?" value={guidance.experience} onChange={value=>setGuidance({...guidance,experience:value as ExperienceContext})} options={[["standard","Tenho experiência"],["first-job","Busco primeiro emprego"],["informal","Experiência informal"],["self-employed","Trabalho por conta própria"]]}/>{guidance.experience==="first-job"&&<CoachTip title="Primeiro emprego também tem conteúdo" text="Você pode destacar formação, cursos, projetos, atividades voluntárias e competências reais. Não é necessário inventar uma experiência profissional."/>}{guidance.experience==="informal"&&<CoachTip title="Experiência informal é experiência" text="Descreva o serviço que você realmente realizou, para quem ou em qual contexto e quais eram suas responsabilidades."/>}{guidance.experience==="self-employed"&&<CoachTip title="Trabalho autônomo pode entrar no currículo" text="Use um título que represente seu trabalho e descreva serviços, responsabilidades e resultados reais. Empresa formal não é obrigatória."/>}</div>{cv.experiences.map((x,i)=><ItemEditor kind="experience" key={x.id} item={x} index={i} onChange={(k,v)=>updateItem("experiences",x.id,k,v)} onRemove={()=>removeItem("experiences",x.id)} onUp={()=>move("experiences",i,-1)} onDown={()=>move("experiences",i,1)}/>)}
      <div id="step-education" className="journeyAnchor"><SectionHead n="03" title="Formação" subtitle="Inclua cursos concluídos ou em andamento. Não é obrigatório informar datas exatas se você não souber." action={()=>addItem("education")}/><ContextChoice label="Como está sua formação?" value={guidance.education} onChange={value=>setGuidance({...guidance,education:value as EducationContext})} options={[["standard","Informar normalmente"],["in-progress","Em andamento"],["no-exact-date","Não sei a data exata"]]}/>{guidance.education==="in-progress"&&<CoachTip title="Formação em andamento é válida" text="No período, você pode escrever “Em andamento” ou informar a previsão de conclusão, se souber."/>}{guidance.education==="no-exact-date"&&<CoachTip title="A data não precisa ser inventada" text="Se você não souber o período exato, informe somente o ano quando souber ou deixe o período em branco."/>}</div>{cv.education.map((x,i)=><ItemEditor kind="education" key={x.id} item={x} index={i} onChange={(k,v)=>updateItem("education",x.id,k,v)} onRemove={()=>removeItem("education",x.id)} onUp={()=>move("education",i,-1)} onDown={()=>move("education",i,1)}/>)}
      {hasDuplicateSkills(cv.skills)&&<CoachTip title="Há competências repetidas" text="Remova duplicatas para deixar a leitura mais objetiva. Mantenha apenas habilidades que você realmente possui."/>}<div id="step-skills" className="journeyAnchor sectionTitle compact"><span>04</span><div><h2>Competências</h2><p>Adicione e organize seus diferenciais.</p></div></div><ListEditor title="Habilidades" items={cv.skills} onAdd={()=>addList("skills")} onChange={(i,v)=>updateList("skills",i,v)} onRemove={i=>removeList("skills",i)}/><div className="subGuidance"><ContextChoice label="Cursos e certificações" value={guidance.courses} onChange={value=>setGuidance({...guidance,courses:value as CoursesContext})} options={[["standard","Tenho cursos para informar"],["none","Não tenho no momento"],["missing-details","Tenho, mas faltam detalhes"]]}/>{guidance.courses==="none"&&<CoachTip title="Tudo bem não ter cursos extras" text="Essa seção é opcional. O currículo pode ser forte com formação, experiências, projetos e competências reais."/>}{guidance.courses==="none"&&cv.courses.some(x=>x.trim())&&<CoachTip title="Seus cursos preenchidos foram preservados" text="Nada foi apagado. Se não quiser mostrá-los neste currículo, você pode ocultar a seção em Design."/>}{guidance.courses==="missing-details"&&<CoachTip title="Não invente datas ou instituições" text="Informe o nome do curso e apenas os detalhes que você souber com segurança. Uma data exata não é obrigatória."/>}</div>{guidance.courses!=="none"&&<ListEditor title="Cursos e certificações" items={cv.courses} onAdd={()=>addList("courses")} onChange={(i,v)=>updateList("courses",i,v)} onRemove={i=>removeList("courses",i)}/>} <ListEditor title="Idiomas" items={cv.languages} onAdd={()=>addList("languages")} onChange={(i,v)=>updateList("languages",i,v)} onRemove={i=>removeList("languages",i)}/>
    </div>:<div className="designPanel"><div className="sectionTitle"><span>✦</span><div><h2>Personalize seu currículo</h2><p>O conteúdo permanece igual ao trocar o visual.</p></div></div><h4>MODELO</h4><div className="templateGrid">{(["essential","modern","executive"] as Template[]).map(t=><button onClick={()=>setTemplate(t)} className={template===t?"selected":""} key={t}><i className={"templateThumb "+t}/><b>{t==="essential"?"Essencial":t==="modern"?"Moderno":"Executivo"}</b></button>)}</div><h4>COR DE DESTAQUE</h4><div className="swatches">{["#087cf0","#2563eb","#0f766e","#b45309","#be123c","#202938"].map(c=><button aria-label={"Cor "+c} className={accent===c?"selected":""} style={{background:c}} onClick={()=>setAccent(c)} key={c}/>)}</div><h4>ESPAÇAMENTO</h4><div className="densityToggle"><button className={density==="comfortable"?"selected":""} onClick={()=>setDensity("comfortable")}>Confortável</button><button className={density==="compact"?"selected":""} onClick={()=>setDensity("compact")}>Compacto</button></div><h4>SEÇÕES DO CURRÍCULO</h4><div className="sectionManager">{sectionOrder.map((key,i)=><div className="sectionManageRow" key={key}><span>{sectionLabel(key)}</span><div><button onClick={()=>moveSection(key,-1)} disabled={i===0}>↑</button><button onClick={()=>moveSection(key,1)} disabled={i===sectionOrder.length-1}>↓</button><button className={visible(key)?"visible":"hidden"} onClick={()=>toggleSection(key)}>{visible(key)?"Visível":"Oculta"}</button></div></div>)}</div><div className="designNote"><b>Design independente do conteúdo</b><p>Troque modelo e cor quando quiser. Suas informações continuam intactas.</p></div></div>}
   </aside>
   <section className="preview"><div className="previewBar"><span>● Prévia em tempo real</span><span>A4 · {template==="essential"?"Essencial":template==="modern"?"Moderno":"Executivo"}</span></div>
    <article className={"paper "+template+" "+density} style={{"--accent":accent} as React.CSSProperties}><header>{cv.photo?<img className="resumePhoto" src={cv.photo} alt=""/>:<div className="initials">{cv.name.split(" ").slice(0,2).map(x=>x[0]).join("")}</div>}<div><h1>{cv.name||"Seu nome"}</h1><h2>{cv.role||"Título profissional"}</h2><p>{[cv.email,cv.phone,cv.city].filter(Boolean).join("  •  ")}</p></div></header>{sectionOrder.filter(visible).map(key=><PreviewSection key={key} sectionKey={key} cv={cv}/>)}</article>
   </section>
  </div><div className="devCredit">CurriculosPRO · Criado por <strong>Felipe Andrade Dev</strong></div>
 </main>
}
function Field({label,value,onChange,area=false,type="text",inputMode,autoComplete,placeholder,hint,maxLength}:{label:string,value:string,onChange:(v:string)=>void,area?:boolean,type?:string,inputMode?:React.HTMLAttributes<HTMLInputElement>["inputMode"],autoComplete?:string,placeholder?:string,hint?:string,maxLength?:number}){return <label className="guidedField"><span>{label}</span>{area?<textarea value={value} placeholder={placeholder} maxLength={maxLength} onChange={e=>onChange(e.target.value)}/>:<input type={type} inputMode={inputMode} autoComplete={autoComplete} placeholder={placeholder} maxLength={maxLength} value={value} onChange={e=>onChange(e.target.value)}/>} {hint&&<small>{hint}</small>}</label>}
function SectionHead({n,title,subtitle,action}:{n:string,title:string,subtitle?:string,action:()=>void}){return <><div className="sectionTitle withAction"><span>{n}</span><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button onClick={action}>＋ Adicionar</button></div></>}
function ItemEditor({item,index,kind,onChange,onRemove,onUp,onDown}:{item:Item,index:number,kind:"experience"|"education",onChange:(k:keyof Item,v:string)=>void,onRemove:()=>void,onUp:()=>void,onDown:()=>void}){return <div className="itemEditor"><div className="itemTop"><b>Item {index+1}</b><div className="itemActions"><button onClick={onUp} title="Mover para cima">↑</button><button onClick={onDown} title="Mover para baixo">↓</button><button className="danger" onClick={onRemove}>Remover</button></div></div><div className="grid2"><Field label="Cargo / Curso" placeholder={kind==="experience"?"Ex.: Assistente Administrativo":"Ex.: Análise e Desenvolvimento de Sistemas"} value={item.title} onChange={v=>onChange("title",v)}/><Field label="Empresa / Instituição" placeholder={kind==="experience"?"Ex.: Empresa Brasileira Ltda.":"Ex.: Faculdade ou instituição"} value={item.subtitle} onChange={v=>onChange("subtitle",v)}/></div><Field label="Período" placeholder="Ex.: jan/2023 — atual" hint="Pode usar mês/ano, somente o ano ou “Atual”." value={item.period} onChange={v=>onChange("period",v)}/><Field area label="Descrição" placeholder={kind==="experience"?"Ex.: Atendimento a clientes, organização de documentos e apoio às rotinas da equipe.":"Opcional: destaque área, projeto, atividade ou aprendizado relevante."} hint={kind==="experience"?"Prefira atividades, responsabilidades e resultados reais. Não invente informações.":"Use apenas quando acrescentar algo relevante à formação."} value={item.description} onChange={v=>onChange("description",v)}/>{kind==="experience"&&item.title.trim()&&item.subtitle.trim()&&!item.description.trim()&&<CoachTip title="Conte o que você fazia" text="Descreva atividades reais. Uma estrutura útil é: ação + atividade + resultado, quando houver um resultado que você possa comprovar."/>}{kind==="education"&&item.title.trim()&&!item.subtitle.trim()&&<CoachTip title="Falta a instituição" text="Se fizer sentido para sua formação, informe onde estudou. Se não houver instituição, você pode deixar em branco."/>}</div>}
function ContextChoice({label,value,onChange,options}:{label:string,value:string,onChange:(value:string)=>void,options:[string,string][]}){return <div className="contextChoice"><b>{label}</b><div>{options.map(([id,text])=><button type="button" key={id} className={value===id?"active":""} onClick={()=>onChange(id)}>{text}</button>)}</div></div>}
function CoachTip({title,text}:{title:string,text:string}){return <div className="coachTip"><span>i</span><p><b>{title}</b><small>{text}</small></p></div>}
function hasDuplicateSkills(items:string[]){const normalized=items.map(x=>x.trim().toLocaleLowerCase("pt-BR")).filter(Boolean);return new Set(normalized).size!==normalized.length}
function ListEditor({title,items,onAdd,onChange,onRemove}:{title:string,items:string[],onAdd:()=>void,onChange:(i:number,v:string)=>void,onRemove:(i:number)=>void}){return <div className="listEditor"><div className="listHead"><b>{title}</b><button onClick={onAdd}>＋ Adicionar</button></div>{items.map((x,i)=><div className="listRow" key={i}><input value={x} onChange={e=>onChange(i,e.target.value)} placeholder={title==="Idiomas"?"Ex.: Inglês — Intermediário":title==="Habilidades"?"Ex.: Excel, Atendimento, Liderança":"Ex.: Excel Avançado — SENAI, 2025"}/><button onClick={()=>onRemove(i)} aria-label="Remover">×</button></div>)}</div>}
function sectionLabel(key:SectionKey){return {summary:"Perfil profissional",experiences:"Experiência",education:"Formação",skills:"Habilidades",languages:"Idiomas",courses:"Cursos e certificações"}[key]}
function PreviewSection({sectionKey,cv}:{sectionKey:SectionKey,cv:CV}){if(sectionKey==="summary")return cv.summary?<section><h3>PERFIL PROFISSIONAL</h3><p>{cv.summary}</p></section>:null;if(sectionKey==="experiences")return cv.experiences.length?<section><h3>EXPERIÊNCIA PROFISSIONAL</h3>{cv.experiences.map(x=><div className="resumeItem" key={x.id}><div className="row"><div><h4>{x.title||"Cargo"}</h4><b>{x.subtitle}</b></div><span>{x.period}</span></div><p>{x.description}</p></div>)}</section>:null;if(sectionKey==="education")return cv.education.length?<section><h3>FORMAÇÃO</h3>{cv.education.map(x=><div className="resumeItem" key={x.id}><div className="row"><div><h4>{x.title||"Curso"}</h4><b>{x.subtitle}</b></div><span>{x.period}</span></div></div>)}</section>:null;if(sectionKey==="skills")return cv.skills.filter(Boolean).length?<section><h3>HABILIDADES</h3><div className="chips">{cv.skills.filter(Boolean).map((x,i)=><i key={x+i}>{x}</i>)}</div></section>:null;if(sectionKey==="languages")return cv.languages.filter(Boolean).length?<section><h3>IDIOMAS</h3>{cv.languages.filter(Boolean).map((x,i)=><p key={x+i}>{x}</p>)}</section>:null;return cv.courses.filter(Boolean).length?<section><h3>CURSOS E CERTIFICAÇÕES</h3><p>{cv.courses.filter(Boolean).join(" • ")}</p></section>:null;}