"use client";
import Image from "next/image";
import {useEffect,useMemo,useRef,useState} from "react";
import {ACTIVE_RESUME_KEY,LEGACY_RESUME_KEY,RESUME_LIBRARY_KEY,ResumeDocument,createResume} from "@/lib/resume";

type Item={id:string;title:string;subtitle:string;period:string;description:string};
type CV={name:string;role:string,email:string;phone:string;city:string;summary:string;photo:string;experiences:Item[];education:Item[];courses:string[];skills:string[];languages:string[]};
type Template="essential"|"modern"|"executive";
type SectionKey="summary"|"experiences"|"education"|"skills"|"languages"|"courses";
const defaultOrder:SectionKey[]=["summary","experiences","education","skills","languages","courses"];
const uid=()=>Math.random().toString(36).slice(2,9);
const initial:CV={name:"Felipe Andrade",photo:"",role:"Desenvolvedor de Software",email:"felipe@email.com",phone:"(11) 99999-9999",city:"São Paulo, SP",summary:"Profissional apaixonado por tecnologia, com foco em criar soluções digitais modernas, eficientes e fáceis de usar.",experiences:[{id:"exp1",title:"Desenvolvedor Full Stack",subtitle:"Empresa Exemplo",period:"2024 — Atual",description:"Desenvolvimento de aplicações web, melhoria de experiências digitais e colaboração com equipes multidisciplinares."}],education:[{id:"edu1",title:"Análise e Desenvolvimento de Sistemas",subtitle:"Instituição de Ensino",period:"2023 — 2025",description:""}],courses:["Desenvolvimento Web"],skills:["JavaScript","TypeScript","React","Comunicação"],languages:["Português — Nativo"]};
const tabs=["Conteúdo","Design"] as const;

export default function Editor(){
 const hydrated=useRef(false),activeId=useRef("");
 const [cv,setCv]=useState(initial),[tab,setTab]=useState<(typeof tabs)[number]>("Conteúdo"),[template,setTemplate]=useState<Template>("essential"),[accent,setAccent]=useState("#087cf0"),[mobilePreview,setMobilePreview]=useState(false),[density,setDensity]=useState<"comfortable"|"compact">("comfortable"),[sectionOrder,setSectionOrder]=useState<SectionKey[]>(defaultOrder),[hidden,setHidden]=useState<SectionKey[]>([]);
 useEffect(()=>{try{const params=new URLSearchParams(location.search),mode=params.get("new"),requested=params.get("template") as Template|null;let docs:ResumeDocument[]=JSON.parse(localStorage.getItem(RESUME_LIBRARY_KEY)||"[]");let doc:ResumeDocument|undefined;if(mode==="blank"||mode==="example"){doc=createResume(mode,requested||"essential");docs=[doc,...docs];localStorage.setItem(RESUME_LIBRARY_KEY,JSON.stringify(docs));history.replaceState({},"","/editor")}else{const id=localStorage.getItem(ACTIVE_RESUME_KEY);doc=docs.find(x=>x.id===id)||docs[0]}if(doc){activeId.current=doc.id;localStorage.setItem(ACTIVE_RESUME_KEY,doc.id);setCv({...initial,...doc.cv});setTemplate(doc.template);setAccent(doc.accent);setDensity(doc.density);setSectionOrder(doc.sectionOrder||defaultOrder);setHidden(doc.hidden||[])}else{const s=localStorage.getItem(LEGACY_RESUME_KEY);if(s){const d=JSON.parse(s);setCv({...initial,...d.cv});setTemplate(d.template||"essential");setAccent(d.accent||"#087cf0");setDensity(d.density||"comfortable");setSectionOrder(d.sectionOrder||defaultOrder);setHidden(d.hidden||[])}}}catch{}finally{hydrated.current=true}},[]);
 useEffect(()=>{if(!hydrated.current)return;try{localStorage.setItem(LEGACY_RESUME_KEY,JSON.stringify({cv,template,accent,density,sectionOrder,hidden}));let docs:ResumeDocument[]=JSON.parse(localStorage.getItem(RESUME_LIBRARY_KEY)||"[]");let id=activeId.current;if(!id){const doc=createResume("blank",template);id=doc.id;activeId.current=id;docs=[doc,...docs];localStorage.setItem(ACTIVE_RESUME_KEY,id)}const now=new Date().toISOString(),found=docs.find(x=>x.id===id),next:ResumeDocument={id,title:found?.title||cv.name||"Meu currículo",createdAt:found?.createdAt||now,updatedAt:now,cv,template,accent,density,sectionOrder,hidden};docs=found?docs.map(x=>x.id===id?next:x):[next,...docs];localStorage.setItem(RESUME_LIBRARY_KEY,JSON.stringify(docs))}catch{}},[cv,template,accent,density,sectionOrder,hidden]);
 const completion=useMemo(()=>Math.round([cv.name,cv.role,cv.email,cv.summary,cv.experiences.length,cv.education.length,cv.skills.length].filter(Boolean).length/7*100),[cv]);
 const set=<K extends keyof CV>(k:K,v:CV[K])=>setCv({...cv,[k]:v});
 const updateItem=(section:"experiences"|"education",id:string,key:keyof Item,value:string)=>setCv({...cv,[section]:cv[section].map(x=>x.id===id?{...x,[key]:value}:x)});
 const addItem=(section:"experiences"|"education")=>setCv({...cv,[section]:[...cv[section],{id:uid(),title:"",subtitle:"",period:"",description:""}]});
 const removeItem=(section:"experiences"|"education",id:string)=>setCv({...cv,[section]:cv[section].filter(x=>x.id!==id)});
 const addList=(key:"courses"|"skills"|"languages")=>set(key,[...cv[key],""]);
 const updateList=(key:"courses"|"skills"|"languages",index:number,value:string)=>set(key,cv[key].map((x,i)=>i===index?value:x));
 const removeList=(key:"courses"|"skills"|"languages",index:number)=>set(key,cv[key].filter((_,i)=>i!==index));
 const move=(section:"experiences"|"education",index:number,dir:-1|1)=>{const next=[...cv[section]],target=index+dir;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setCv({...cv,[section]:next})};
 const onPhoto=(file?:File)=>{if(!file||file.size>2_500_000)return;const reader=new FileReader();reader.onload=()=>{const img=new window.Image();img.onload=()=>{const canvas=document.createElement("canvas"),max=480,scale=Math.min(1,max/Math.max(img.width,img.height));canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d")?.drawImage(img,0,0,canvas.width,canvas.height);set("photo",canvas.toDataURL("image/jpeg",.82))};img.src=String(reader.result)};reader.readAsDataURL(file)};
 const moveSection=(key:SectionKey,dir:-1|1)=>{const i=sectionOrder.indexOf(key),target=i+dir;if(target<0||target>=sectionOrder.length)return;const next=[...sectionOrder];[next[i],next[target]]=[next[target],next[i]];setSectionOrder(next)};
 const toggleSection=(key:SectionKey)=>setHidden(hidden.includes(key)?hidden.filter(x=>x!==key):[...hidden,key]);
 const visible=(key:SectionKey)=>!hidden.includes(key);
 return <main className="editor">
  <header className="editorHead"><a className="brand brandImage editorLogo" href="/"><Image src="/brand/logo-transparent.png" alt="CurriculosPRO" width={155} height={58} priority /></a><a className="backLibrary" href="/curriculos">← Meus currículos</a><div className="progress"><i style={{width:completion+"%"}}/><span>{completion}% completo</span></div><div className="save">● Salvo automaticamente</div><button className="mobileView" onClick={()=>setMobilePreview(!mobilePreview)}>{mobilePreview?"Editar":"Visualizar"}</button><button onClick={()=>window.print()} className="download">Baixar PDF ↓</button></header>
  <div className={"workspace "+(mobilePreview?"showPreview":"")}>
   <aside className="side">
    <div className="editorTabs">{tabs.map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
    {tab==="Conteúdo"?<div className="formBody">
      <div className="sectionTitle"><span>01</span><div><h2>Informações pessoais</h2><p>Comece pelo essencial.</p></div></div>
      <div className="photoControl"><div className="photoPreview">{cv.photo?<img src={cv.photo} alt="Foto do currículo"/>:<span>{cv.name.split(" ").slice(0,2).map(x=>x[0]).join("")||"CV"}</span>}</div><div><b>Foto profissional <small>opcional</small></b><p>Use uma foto clara e profissional. Você pode remover quando quiser.</p><label className="photoButton">Escolher foto<input type="file" accept="image/*" onChange={e=>onPhoto(e.target.files?.[0])}/></label>{cv.photo&&<button className="removePhoto" onClick={()=>set("photo","")}>Remover foto</button>}</div></div><div className="grid2"><Field label="Nome completo" value={cv.name} onChange={v=>set("name",v)}/><Field label="Título profissional" value={cv.role} onChange={v=>set("role",v)}/><Field label="E-mail" value={cv.email} onChange={v=>set("email",v)}/><Field label="Telefone" value={cv.phone} onChange={v=>set("phone",v)}/></div><Field label="Cidade / Estado" value={cv.city} onChange={v=>set("city",v)}/><Field area label="Resumo profissional" value={cv.summary} onChange={v=>set("summary",v)}/>
      <SectionHead n="02" title="Experiência" action={()=>addItem("experiences")}/>{cv.experiences.map((x,i)=><ItemEditor key={x.id} item={x} index={i} onChange={(k,v)=>updateItem("experiences",x.id,k,v)} onRemove={()=>removeItem("experiences",x.id)} onUp={()=>move("experiences",i,-1)} onDown={()=>move("experiences",i,1)}/>)}
      <SectionHead n="03" title="Formação" action={()=>addItem("education")}/>{cv.education.map((x,i)=><ItemEditor key={x.id} item={x} index={i} onChange={(k,v)=>updateItem("education",x.id,k,v)} onRemove={()=>removeItem("education",x.id)} onUp={()=>move("education",i,-1)} onDown={()=>move("education",i,1)}/>)}
      <div className="sectionTitle compact"><span>04</span><div><h2>Competências</h2><p>Adicione e organize seus diferenciais.</p></div></div><ListEditor title="Habilidades" items={cv.skills} onAdd={()=>addList("skills")} onChange={(i,v)=>updateList("skills",i,v)} onRemove={i=>removeList("skills",i)}/><ListEditor title="Cursos e certificações" items={cv.courses} onAdd={()=>addList("courses")} onChange={(i,v)=>updateList("courses",i,v)} onRemove={i=>removeList("courses",i)}/><ListEditor title="Idiomas" items={cv.languages} onAdd={()=>addList("languages")} onChange={(i,v)=>updateList("languages",i,v)} onRemove={i=>removeList("languages",i)}/>
    </div>:<div className="designPanel"><div className="sectionTitle"><span>✦</span><div><h2>Personalize seu currículo</h2><p>O conteúdo permanece igual ao trocar o visual.</p></div></div><h4>MODELO</h4><div className="templateGrid">{(["essential","modern","executive"] as Template[]).map(t=><button onClick={()=>setTemplate(t)} className={template===t?"selected":""} key={t}><i className={"templateThumb "+t}/><b>{t==="essential"?"Essencial":t==="modern"?"Moderno":"Executivo"}</b></button>)}</div><h4>COR DE DESTAQUE</h4><div className="swatches">{["#087cf0","#2563eb","#0f766e","#b45309","#be123c","#202938"].map(c=><button aria-label={"Cor "+c} className={accent===c?"selected":""} style={{background:c}} onClick={()=>setAccent(c)} key={c}/>)}</div><h4>ESPAÇAMENTO</h4><div className="densityToggle"><button className={density==="comfortable"?"selected":""} onClick={()=>setDensity("comfortable")}>Confortável</button><button className={density==="compact"?"selected":""} onClick={()=>setDensity("compact")}>Compacto</button></div><h4>SEÇÕES DO CURRÍCULO</h4><div className="sectionManager">{sectionOrder.map((key,i)=><div className="sectionManageRow" key={key}><span>{sectionLabel(key)}</span><div><button onClick={()=>moveSection(key,-1)} disabled={i===0}>↑</button><button onClick={()=>moveSection(key,1)} disabled={i===sectionOrder.length-1}>↓</button><button className={visible(key)?"visible":"hidden"} onClick={()=>toggleSection(key)}>{visible(key)?"Visível":"Oculta"}</button></div></div>)}</div><div className="designNote"><b>Design independente do conteúdo</b><p>Troque modelo e cor quando quiser. Suas informações continuam intactas.</p></div></div>}
   </aside>
   <section className="preview"><div className="previewBar"><span>● Prévia em tempo real</span><span>A4 · {template==="essential"?"Essencial":template==="modern"?"Moderno":"Executivo"}</span></div>
    <article className={"paper "+template+" "+density} style={{"--accent":accent} as React.CSSProperties}><header>{cv.photo?<img className="resumePhoto" src={cv.photo} alt=""/>:<div className="initials">{cv.name.split(" ").slice(0,2).map(x=>x[0]).join("")}</div>}<div><h1>{cv.name||"Seu nome"}</h1><h2>{cv.role||"Título profissional"}</h2><p>{[cv.email,cv.phone,cv.city].filter(Boolean).join("  •  ")}</p></div></header>{sectionOrder.filter(visible).map(key=><PreviewSection key={key} sectionKey={key} cv={cv}/>)}</article>
   </section>
  </div><div className="devCredit">CurriculosPRO · Criado por <strong>Felipe Andrade Dev</strong></div>
 </main>
}
function Field({label,value,onChange,area=false}:{label:string,value:string,onChange:(v:string)=>void,area?:boolean}){return <label>{label}{area?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function SectionHead({n,title,action}:{n:string,title:string,action:()=>void}){return <div className="sectionTitle withAction"><span>{n}</span><h2>{title}</h2><button onClick={action}>＋ Adicionar</button></div>}
function ItemEditor({item,index,onChange,onRemove,onUp,onDown}:{item:Item,index:number,onChange:(k:keyof Item,v:string)=>void,onRemove:()=>void,onUp:()=>void,onDown:()=>void}){return <div className="itemEditor"><div className="itemTop"><b>Item {index+1}</b><div className="itemActions"><button onClick={onUp} title="Mover para cima">↑</button><button onClick={onDown} title="Mover para baixo">↓</button><button className="danger" onClick={onRemove}>Remover</button></div></div><div className="grid2"><Field label="Cargo / Curso" value={item.title} onChange={v=>onChange("title",v)}/><Field label="Empresa / Instituição" value={item.subtitle} onChange={v=>onChange("subtitle",v)}/></div><Field label="Período" value={item.period} onChange={v=>onChange("period",v)}/><Field area label="Descrição" value={item.description} onChange={v=>onChange("description",v)}/></div>}
function ListEditor({title,items,onAdd,onChange,onRemove}:{title:string,items:string[],onAdd:()=>void,onChange:(i:number,v:string)=>void,onRemove:(i:number)=>void}){return <div className="listEditor"><div className="listHead"><b>{title}</b><button onClick={onAdd}>＋ Adicionar</button></div>{items.map((x,i)=><div className="listRow" key={i}><input value={x} onChange={e=>onChange(i,e.target.value)} placeholder={"Adicionar "+title.toLowerCase()}/><button onClick={()=>onRemove(i)} aria-label="Remover">×</button></div>)}</div>}
function sectionLabel(key:SectionKey){return {summary:"Perfil profissional",experiences:"Experiência",education:"Formação",skills:"Habilidades",languages:"Idiomas",courses:"Cursos e certificações"}[key]}
function PreviewSection({sectionKey,cv}:{sectionKey:SectionKey,cv:CV}){if(sectionKey==="summary")return cv.summary?<section><h3>PERFIL PROFISSIONAL</h3><p>{cv.summary}</p></section>:null;if(sectionKey==="experiences")return cv.experiences.length?<section><h3>EXPERIÊNCIA PROFISSIONAL</h3>{cv.experiences.map(x=><div className="resumeItem" key={x.id}><div className="row"><div><h4>{x.title||"Cargo"}</h4><b>{x.subtitle}</b></div><span>{x.period}</span></div><p>{x.description}</p></div>)}</section>:null;if(sectionKey==="education")return cv.education.length?<section><h3>FORMAÇÃO</h3>{cv.education.map(x=><div className="resumeItem" key={x.id}><div className="row"><div><h4>{x.title||"Curso"}</h4><b>{x.subtitle}</b></div><span>{x.period}</span></div></div>)}</section>:null;if(sectionKey==="skills")return cv.skills.filter(Boolean).length?<section><h3>HABILIDADES</h3><div className="chips">{cv.skills.filter(Boolean).map((x,i)=><i key={x+i}>{x}</i>)}</div></section>:null;if(sectionKey==="languages")return cv.languages.filter(Boolean).length?<section><h3>IDIOMAS</h3>{cv.languages.filter(Boolean).map((x,i)=><p key={x+i}>{x}</p>)}</section>:null;return cv.courses.filter(Boolean).length?<section><h3>CURSOS E CERTIFICAÇÕES</h3><p>{cv.courses.filter(Boolean).join(" • ")}</p></section>:null;}