"use client";
import Image from "next/image";
import Link from "next/link";
import {useEffect,useState} from "react";
import {ACTIVE_RESUME_KEY,LEGACY_RESUME_KEY,RESUME_LIBRARY_KEY,ResumeDocument,createResume,parseBackup} from "@/lib/resume";

export default function ResumesPage(){
 const [items,setItems]=useState<ResumeDocument[]>([]);
 useEffect(()=>{try{let list:ResumeDocument[]=JSON.parse(localStorage.getItem(RESUME_LIBRARY_KEY)||"[]");if(!list.length){const legacy=localStorage.getItem(LEGACY_RESUME_KEY);if(legacy){const old=JSON.parse(legacy),doc=createResume("blank",old.template||"essential");doc.title=old.cv?.name?("Currículo — "+old.cv.name):"Meu currículo";doc.cv={...doc.cv,...old.cv};doc.accent=old.accent||doc.accent;doc.density=old.density||doc.density;doc.sectionOrder=old.sectionOrder||doc.sectionOrder;doc.hidden=old.hidden||[];list=[doc];localStorage.setItem(RESUME_LIBRARY_KEY,JSON.stringify(list))}}setItems(list)}catch{}},[]);
 const save=(list:ResumeDocument[])=>{setItems(list);localStorage.setItem(RESUME_LIBRARY_KEY,JSON.stringify(list))};
 const open=(id:string)=>{localStorage.setItem(ACTIVE_RESUME_KEY,id);location.href="/editor"};
 const add=(mode:"blank"|"example")=>{const doc=createResume(mode);save([doc,...items]);open(doc.id)};
 const rename=(doc:ResumeDocument)=>{const title=prompt("Nome deste currículo:",doc.title)?.trim();if(title)save(items.map(x=>x.id===doc.id?{...x,title,updatedAt:new Date().toISOString()}:x))};
 const duplicate=(doc:ResumeDocument)=>{const now=new Date().toISOString(),copy={...doc,id:Date.now().toString(36),title:doc.title+" — cópia",createdAt:now,updatedAt:now,cv:{...doc.cv,experiences:doc.cv.experiences.map(x=>({...x})),education:doc.cv.education.map(x=>({...x}))}};save([copy,...items])};
 const remove=(id:string)=>{if(confirm("Excluir este currículo? Esta ação não pode ser desfeita."))save(items.filter(x=>x.id!==id))};
 const exportAll=()=>{const blob=new Blob([JSON.stringify({product:"CurriculosPRO",version:3,exportedAt:new Date().toISOString(),resumes:items},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="curriculospro-backup.json";a.click();URL.revokeObjectURL(a.href)};
 const importFile=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const incoming=parseBackup(String(reader.result));save([...incoming.map((x:ResumeDocument)=>({...x,id:Date.now().toString(36)+Math.random().toString(36).slice(2,5),updatedAt:new Date().toISOString()})),...items])}catch{alert("Arquivo de backup inválido.")}};reader.readAsText(file)};
 return <main className="libraryPage"><header className="nav shell"><Link className="brand brandImage" href="/"><Image src="/brand/logo-transparent.png" alt="CurriculosPRO" width={190} height={72} priority/></Link><nav><Link href="/modelos">Modelos</Link><button className="ghostAction" onClick={exportAll}>Exportar backup</button></nav></header><section className="libraryHero shell"><div><span className="pill">SEUS CURRÍCULOS</span><h1>Um perfil. Várias oportunidades.</h1><p>Crie versões diferentes do seu currículo para cada objetivo profissional. Tudo fica salvo neste dispositivo.</p></div><div className="libraryActions"><button className="primary" onClick={()=>add("blank")}>＋ Novo currículo</button><button className="secondary" onClick={()=>add("example")}>Usar exemplo</button><label className="secondary importButton">Importar backup<input type="file" accept=".json,application/json" onChange={e=>importFile(e.target.files?.[0])}/></label></div></section><section className="resumeLibrary shell">{items.length?items.map(doc=><article className="resumeCard" key={doc.id}><div className={"resumeCardThumb "+doc.template}><i style={{background:doc.accent}}/><span/><span/><span/></div><div className="resumeCardBody"><small>{doc.template==="essential"?"ESSENCIAL":doc.template==="modern"?"MODERNO":"EXECUTIVO"}</small><h2>{doc.title}</h2><p>{doc.cv.role||"Sem título profissional"} · atualizado {new Date(doc.updatedAt).toLocaleDateString("pt-BR")}</p><div><button className="cardPrimary" onClick={()=>open(doc.id)}>Continuar editando</button><button onClick={()=>rename(doc)}>Renomear</button><button onClick={()=>duplicate(doc)}>Duplicar</button><button className="dangerText" onClick={()=>remove(doc.id)}>Excluir</button></div></div></article>):<div className="emptyLibrary"><b>Seu espaço está pronto.</b><p>Crie um currículo do zero ou abra um exemplo para conhecer o editor.</p><button className="primary" onClick={()=>add("blank")}>Criar primeiro currículo</button></div>}</section><div className="devCredit">CurriculosPRO · Criado por <strong>Felipe Andrade Dev</strong></div></main>
}
