"use client";
import {useEffect,useState} from "react";
import {CloudSync} from "./cloud-sync";
import {SiteHeader} from "@/components/site-header";
import {SiteFooter} from "@/components/site-footer";
import {ACTIVE_RESUME_KEY,LEGACY_RESUME_KEY,RESUME_LIBRARY_KEY,ResumeDocument,createResume,parseBackup,readRecovery,storeRecovery,cloneResume,migrateLegacyResume} from "@/lib/resume";

export default function ResumesPage(){
 const [items,setItems]=useState<ResumeDocument[]>([]),[recoveryDate,setRecoveryDate]=useState("");
 useEffect(()=>{try{let list:ResumeDocument[]=JSON.parse(localStorage.getItem(RESUME_LIBRARY_KEY)||"[]");if(!list.length){const legacy=localStorage.getItem(LEGACY_RESUME_KEY);if(legacy){const doc=migrateLegacyResume(legacy);list=[doc];localStorage.setItem(RESUME_LIBRARY_KEY,JSON.stringify(list))}}setItems(list);const recovery=readRecovery();if(recovery)setRecoveryDate(recovery.createdAt)}catch{}},[]);
 const save=(list:ResumeDocument[])=>{setItems(list);localStorage.setItem(RESUME_LIBRARY_KEY,JSON.stringify(list))};
 const open=(id:string)=>{localStorage.setItem(ACTIVE_RESUME_KEY,id);location.href="/editor"};
 const add=(mode:"blank"|"example")=>{const doc=createResume(mode);save([doc,...items]);open(doc.id)};
 const rename=(doc:ResumeDocument)=>{const title=prompt("Nome deste currículo:",doc.title)?.trim();if(title)save(items.map(x=>x.id===doc.id?{...x,title,updatedAt:new Date().toISOString()}:x))};
 const duplicate=(doc:ResumeDocument)=>save([cloneResume(doc),...items]);
 const remove=(id:string)=>{if(confirm("Excluir este currículo? Você poderá restaurar a última recuperação.")){storeRecovery(items,"delete");setRecoveryDate(new Date().toISOString());save(items.filter(x=>x.id!==id))}};
 const restore=()=>{const recovery=readRecovery();if(recovery&&confirm("Restaurar a biblioteca para o estado salvo antes da última alteração?"))save(recovery.resumes)};
 const exportAll=()=>{const blob=new Blob([JSON.stringify({product:"CurriculosPRO",version:3,exportedAt:new Date().toISOString(),resumes:items},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="curriculospro-backup.json";a.click();URL.revokeObjectURL(a.href)};
 const importFile=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const incoming=parseBackup(String(reader.result));storeRecovery(items,"import");setRecoveryDate(new Date().toISOString());save([...incoming.map((x:ResumeDocument)=>cloneResume(x,x.title)),...items])}catch{alert("Arquivo de backup inválido.")}};reader.readAsText(file)};
 return <main className="libraryPage"><SiteHeader active="curriculos"/><section className="libraryUtility shell"><span className="planBadge">PLANO FREE</span><button className="ghostAction" onClick={exportAll}>Exportar backup</button></section><section className="libraryHero shell"><div><span className="pill">SEUS CURRÍCULOS</span><h1>Um perfil. Várias oportunidades.</h1><p>Crie versões diferentes do seu currículo para cada objetivo profissional. Tudo fica salvo neste dispositivo.</p></div><div className="libraryActions"><button className="primary" onClick={()=>add("blank")}>＋ Novo currículo</button><button className="secondary" onClick={()=>add("example")}>Usar exemplo</button><label className="secondary importButton">Importar backup<input type="file" accept=".json,application/json" onChange={e=>importFile(e.target.files?.[0])}/></label></div></section><section className="cloudBar shell"><CloudSync/></section><section className="storageStatus shell"><div><b>✓ Salvo neste dispositivo</b><span>Seus currículos continuam disponíveis neste navegador. Exporte um backup para guardar uma cópia fora dele.</span></div>{recoveryDate&&<button onClick={restore}>↶ Restaurar última recuperação</button>}</section><section className="resumeLibrary shell">{items.length?items.map(doc=><article className="resumeCard" key={doc.id}><div className={"resumeCardThumb "+doc.template}><i style={{background:doc.accent}}/><span/><span/><span/></div><div className="resumeCardBody"><small>{doc.template==="essential"?"ESSENCIAL":doc.template==="modern"?"MODERNO":"EXECUTIVO"}</small><h2>{doc.title}</h2><p>{doc.cv.role||"Sem título profissional"} · atualizado {new Date(doc.updatedAt).toLocaleDateString("pt-BR")}</p><div><button className="cardPrimary" onClick={()=>open(doc.id)}>Continuar editando</button><button onClick={()=>rename(doc)}>Renomear</button><button onClick={()=>duplicate(doc)}>Duplicar</button><button className="dangerText" onClick={()=>remove(doc.id)}>Excluir</button></div></div></article>):<div className="emptyLibrary"><b>Seu espaço está pronto.</b><p>Crie um currículo do zero ou abra um exemplo para conhecer o editor.</p><button className="primary" onClick={()=>add("blank")}>Criar primeiro currículo</button></div>}</section><SiteFooter/></main>
}
