"use client";
import {useEffect,useState} from "react";
import {PROFESSIONAL_PROFILE_KEY,ProfessionalProfile,ResumeItem,emptyProfessionalProfile,isProfessionalProfile,uid} from "@/lib/resume";
import {SiteHeader} from "@/components/site-header";
import {SiteFooter} from "@/components/site-footer";

type ListKey="courses"|"skills"|"languages";
export default function ProfessionalProfilePage(){
 const [profile,setProfile]=useState<ProfessionalProfile>(emptyProfessionalProfile()),[ready,setReady]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(PROFESSIONAL_PROFILE_KEY);if(raw){const parsed=JSON.parse(raw);if(isProfessionalProfile(parsed))setProfile(parsed)}}catch{}finally{setReady(true)}},[]);
 useEffect(()=>{if(!ready)return;const next={...profile,updatedAt:new Date().toISOString()};localStorage.setItem(PROFESSIONAL_PROFILE_KEY,JSON.stringify(next))},[profile,ready]);
 const setText=(key:"name"|"email"|"phone"|"city",value:string)=>setProfile({...profile,[key]:value});
 const updateItem=(section:"experiences"|"education",id:string,key:keyof ResumeItem,value:string)=>setProfile({...profile,[section]:profile[section].map(x=>x.id===id?{...x,[key]:value}:x)});
 const addItem=(section:"experiences"|"education")=>setProfile({...profile,[section]:[...profile[section],{id:uid(),title:"",subtitle:"",period:"",description:""}]});
 const removeItem=(section:"experiences"|"education",id:string)=>setProfile({...profile,[section]:profile[section].filter(x=>x.id!==id)});
 const updateList=(key:ListKey,index:number,value:string)=>setProfile({...profile,[key]:profile[key].map((x,i)=>i===index?value:x)});
 const addList=(key:ListKey)=>setProfile({...profile,[key]:[...profile[key],""]});
 const removeList=(key:ListKey,index:number)=>setProfile({...profile,[key]:profile[key].filter((_,i)=>i!==index)});
 return <main className="profilePage"><SiteHeader active="curriculos"/><section className="profileHero shell"><div><span className="pill">PERFIL PROFISSIONAL</span><h1>Sua trajetória, pronta para ser reutilizada.</h1><p>Guarde aqui fatos profissionais que não mudam a cada vaga. Seus currículos continuam independentes: nada é alterado automaticamente.</p></div><a className="secondary" href="/curriculos">← Voltar aos currículos</a></section><section className="profileEditor shell"><aside><b>O que fica no perfil?</b><p>Contato, experiências, formação, cursos, competências e idiomas.</p><b>O que fica em cada currículo?</b><p>Título profissional, resumo, seleção de conteúdo, modelo, ordem e aparência.</p><small>O CurriculosPRO não completa informações que você não forneceu.</small></aside><div className="profileForm"><ProfileSection title="Dados pessoais" subtitle="Informações que você costuma reutilizar."><div className="profileGrid"><ProfileField label="Nome completo" value={profile.name} onChange={v=>setText("name",v)}/><ProfileField label="E-mail" value={profile.email} onChange={v=>setText("email",v)}/><ProfileField label="Telefone" value={profile.phone} onChange={v=>setText("phone",v)}/><ProfileField label="Cidade / Estado" value={profile.city} onChange={v=>setText("city",v)}/></div></ProfileSection><ProfileSection title="Experiências" subtitle="Empregos, trabalhos autônomos, estágios, projetos ou experiências informais reais." action={()=>addItem("experiences")}>{profile.experiences.map((item,i)=><ProfileItem key={item.id} item={item} label={"Experiência "+(i+1)} onChange={(k,v)=>updateItem("experiences",item.id,k,v)} onRemove={()=>removeItem("experiences",item.id)}/>)}</ProfileSection><ProfileSection title="Formação" subtitle="Inclua somente o que você sabe com segurança." action={()=>addItem("education")}>{profile.education.map((item,i)=><ProfileItem key={item.id} item={item} label={"Formação "+(i+1)} onChange={(k,v)=>updateItem("education",item.id,k,v)} onRemove={()=>removeItem("education",item.id)}/>)}</ProfileSection>{([["skills","Competências"],["courses","Cursos e certificações"],["languages","Idiomas"]] as [ListKey,string][]).map(([key,title])=><ProfileSection key={key} title={title} action={()=>addList(key)}>{profile[key].map((value,i)=><div className="profileListRow" key={i}><input value={value} onChange={e=>updateList(key,i,e.target.value)} placeholder={key==="skills"?"Ex.: Excel":key==="languages"?"Ex.: Inglês — Intermediário":"Ex.: Excel Avançado"}/><button onClick={()=>removeList(key,i)}>Remover</button></div>)}</ProfileSection>)}</div></section><SiteFooter/></main>
}
function ProfileSection({title,subtitle,action,children}:{title:string;subtitle?:string;action?:()=>void;children:React.ReactNode}){return <section className="profileBlock"><header><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action&&<button onClick={action}>＋ Adicionar</button>}</header>{children}</section>}
function ProfileField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)}/></label>}
function ProfileItem({item,label,onChange,onRemove}:{item:ResumeItem;label:string;onChange:(k:keyof ResumeItem,v:string)=>void;onRemove:()=>void}){return <div className="profileItem"><div><b>{label}</b><button onClick={onRemove}>Remover</button></div><div className="profileGrid"><ProfileField label="Título / função" value={item.title} onChange={v=>onChange("title",v)}/><ProfileField label="Empresa / instituição" value={item.subtitle} onChange={v=>onChange("subtitle",v)}/><ProfileField label="Período" value={item.period} onChange={v=>onChange("period",v)}/></div><label><span>Descrição <small>opcional</small></span><textarea rows={3} value={item.description} onChange={e=>onChange("description",e.target.value)}/></label></div>}
